version: '2'
services:

  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DB_NAME=urlshortdb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SCHEMA=urlshortschema

  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=urlshortdb